### ISSUE TITLE
Tracking bug: API docs issues affecting the site

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1601]
This list includes issues affecting the core library API docs (https://www.polymer-project.org/1.0/docs/api/Polymer.Base and friends).
- [x]  [API Docs: Change section Listbox to visible navigation iron-component-page#96](PolymerElements/iron-component-page#96), [iron-component-page#29](PolymerElements/iron-component-page#29). NOT FIXED for iron-component-page, but fixed on our site. Still need to re-examine icp.
- [x]  [API docs are slow to load #1600](#1600) 
- [x] [Make API docs use released version #1528](#1528)
- [x] [Properties that take functions as input should still be listed as properties, not methods iron-component-page#77](https://github.com/PolymerElements/iron-component-page/issues/77)
- [ ] [Show attributes for properties](https://github.com/PolymerElements/iron-component-page/issues/32) (also auto-generated events).
- [x] [Signature overrides JSDoc tags](https://github.com/Polymer/hydrolysis/issues/231). (Only an issue for 1.x and/or ES5 code now because ES6 supports these signatures in a way that avoids the problem.)

There are other issues that are important to the catalog docs, but not so important for this case (in particular, cross-element links using `@see` or `{@link }`.

**Comment by arthurevans** [comment]
Several issues fixed (or worked around) in the new website. Several still outstanding.

**Comment by katejeffreys** [comment]
@arthurevans Are there things here that are still things?

**Comment by arthurevans** [comment]
Bottom two are still issues, but fairly low priority.

**Comment by arthurevans** [comment]
The only issue left open here for 2.x+ docs is really specific to element docs, not to the p-p.org website. So closing this issue, at long last!
